### ISSUE TITLE
Add warning if using plugin AuctionHouse

### ISSUE THREAD

**Issue by SrBedrock** [Pemigrade/botflop#11]
Would it be possible to add the AuctionHouse plugin to the list of bad plugins when reviewing timings?
In addition to the performance problem there are other exploits that I will not explain here..

![image](https://user-images.githubusercontent.com/51332006/104527371-565ffb00-55e3-11eb-86d2-a1957f24ecd6.png)

![image](https://user-images.githubusercontent.com/51332006/104527518-ab037600-55e3-11eb-9ff8-b9b037900f2a.png)

![image](https://user-images.githubusercontent.com/51332006/104527396-637cea00-55e3-11eb-96e8-ed8e5fad0dea.png)

![image](https://user-images.githubusercontent.com/51332006/104527405-67107100-55e3-11eb-976c-d38113c44a01.png)

![image](https://user-images.githubusercontent.com/51332006/104527410-6a0b6180-55e3-11eb-8fea-7e4d0a34a2a2.png)

**Comment by DrBot7** [comment]
I had actually been suggesting that people use AuctionHouse instead of CrazyAuctions. I'll remove that suggestion, but I don't think I want to add AuctionHouse to the lit of bad plugins just yet. When I finally make the bot read the actual timings part of the reports, it should be able to dynamically detect laggy plugins.
